
name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: yourACRname.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
       - uses: actions/checkout@v2
       - name: Build the stack
        run: docker-compose up -d
       - name: Test
        run: | 
          docker run --network container:online-shopping-system-advanced_web 
          docker push team7acr.azurecr.io/appdb:${{ github.sha }}
      #- run: |
       #   docker build . -t yourACRname.azurecr.io/appdb:${{ github.sha }}
#          docker push yourACRn.azurecr.io/appdb:${{ github.sha }}
